---
title: "Alcohol consumption as function of latitude and wealth"
author: "JP"
date: "July 7, 2017"
output: github_document
---

```{r}
library(tidyverse)
library(readr)
library(stringr)
library(forcats)
```

```{r data paths}
# https://github.com/fivethirtyeight/data/tree/master/alcohol-consumption
data_drinks <- "../data/drinks.csv"

# "https://developers.google.com/public-data/docs/canonical/countries_csv"
data_longlat <- "../data/long_lat.csv"

# http://data.worldbank.org/indicator/NY.GDP.PCAP.PP.CD
data_ppp <- "../data/ppp/API_NY.GDP.PCAP.PP.CD_DS2_en_csv_v2.csv"
```

```{r load data, include=FALSE}
# drinks data
read_lines(data_drinks, n_max = 5)

drinks <- read_csv(data_drinks) %>% 
  rename(total = total_litres_of_pure_alcohol)

# latitude data
read_lines(data_longlat, n_max = 5)

lat <- read_csv(data_longlat) %>% 
  rename(abbr = country)

# ppp data
readLines(data_ppp, n = 10)

ppp <- 
  read_csv(data_ppp, skip = 4) %>% 
  select(country = `Country Name`, abbr = `Country Code`, ppp = `2016`)

# join the data 
d <- drinks %>% 
  left_join(lat, by = c("country" = "name")) %>% 
  left_join(ppp, by = "country")
```

Poking around: 
```{r}
d %>% arrange(desc(total))

d %>% filter(str_detect(country, "R")) %>% arrange(desc(country))

d %>% filter(country == "Russian Federation")
```


```{r}
d %>% 
  mutate(
    lat_abs = abs(latitude),
    ns = ifelse(latitude > 0, "North",
      ifelse(latitude <= 0, "South", NA))
  ) %>% 
  filter(complete.cases(ns)) %>% 
  ggplot(aes(x = lat_abs, y = total, color = ns)) + 
  geom_point() + 
  geom_smooth() + 
  scale_color_discrete("Hemisphere") + 
  scale_x_continuous(breaks = seq(0, 80, by = 10)) + 
  labs(
    title = "Drinking spikes when you are farther than 30-degrees north from the equator,\nespecially so in the northern hemisphere.",
    x = "Absolute Value for Latitude",
    y = "Liters of alcohol consumed per person per year"
  )
```

```{r}
d %>% 
  ggplot(aes(x = latitude, y = total)) + 
  geom_point(alpha = .75) + 
  geom_smooth() + 
  geom_vline(xintercept = 0, color = "green") + 
  scale_color_discrete("Hemisphere") + 
  scale_x_continuous(breaks = seq(-45, 65, by = 5)) + 
  labs(
    title = "Drinking spikes when you are farther than 30-degrees north from the equator,\nespecially so in the northern hemisphere.",
    x = "Latitude",
    y = "Liters of alcohol consumed per person per year"
  )
```

```{r}
d %>% 
  ggplot(aes(x = latitude, y = total)) + 
  geom_boxplot(aes(group = cut_width(latitude, 5))) + 
  scale_x_continuous(breaks = seq(-45, 65, by = 5)) + 
  geom_vline(xintercept = 0, color = "blue") + 
  labs(
    title = "Drinking spikes when you are farther than 30-degrees north from the equator,\nespecially so in the northern hemisphere.",
    x = "Latitude",
    y = "Liters of alcohol consumed per person per year"
  )
```

```{r}
d %>% 
  ggplot(aes(x = ppp, y = total)) + 
  geom_point(alpha = .75) + 
  geom_smooth() 

d %>% 
  filter(ppp < 5e4) %>% 
  ggplot(aes(x = ppp, y = total)) + 
  geom_point(alpha = .75) + 
  geom_smooth() + 
  labs(
    title = "The poor drink less.",
    x = "GDP per Person (PPP) in USD",
    y = "Liters of alcohol consumed per person per year"
  ) 
```

```{r}
d %>% 
  mutate(
    ppp_f = ifelse(ppp <= 15000, "low",
      ifelse(ppp > 15000 & ppp < 30000, "medium",
      ifelse(ppp >= 30000, "high", NA)
    )),
    ppp_f = factor(ppp_f, levels = c("low", "medium", "high"))
  ) %>% 
  filter(complete.cases(ppp_f)) %>% 
  ggplot(aes(x = latitude, y = total, color = fct_rev(ppp_f))) + 
  geom_point(alpha = .75) + 
  geom_smooth() + 
  geom_vline(xintercept = 0, color = "black") + 
  scale_color_discrete("PPP") + 
  scale_x_continuous(breaks = seq(-45, 65, by = 5)) + 
  labs(
    title = "Wealthy countries buck the trend of higher drinking in the far north.",
    x = "Latitude",
    y = "Liters of alcohol consumed per person per year"
  )
```

TBD: Add in religion as a variable. 

